### ISSUE TITLE
报错：服务器内部发生未知错误!详情:java.net.ProtocolException

### ISSUE THREAD

**Issue by conch2** [jianjianai/NewBingGoGo-Web#34]
我在搭建好后随便问了一句就出现报错。
### 环境：
Windows10
java 18.0.2.1 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
### 具体报错信息：
服务器内部发生未知错误!详情:java.net.ProtocolException: Server redirected too many times (20) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2005) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) at cn.jja8.newbinggogo.NewBingGoGoServer.goUrl(NewBingGoGoServer.java:236) at cn.jja8.newbinggogo.NewBingGoGoServer.goUrl(NewBingGoGoServer.java:155) at cn.jja8.newbinggogo.NewBingGoGoServer.serveHttp(NewBingGoGoServer.java:57) at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:862) at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:901) at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:148) at java.base/java.lang.Thread.run(Thread.java:833)
### 详情如图
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/74294886/6c6ae591-ffef-458c-becb-426cd2f8a775)

**Comment by jianjianai** [comment]
重定向次数过多，是因为服务端部署在国内导致的。将服务端部署到国外即可解决问题。
