### ISSUE TITLE
通过jar允许，为啥会报重定向太多

### ISSUE THREAD

**Issue by lele0601** [jianjianai/NewBingGoGo-Web#71]
服务器内部发生未知错误!详情:java.net.ProtocolException: Server redirected too many times (20) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2005) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) at cn.jja8.newbinggogo.NewBingGoGoServer.goUrl(NewBingGoGoServer.java:268) at cn.jja8.newbinggogo.NewBingGoGoServer.goUrl(NewBingGoGoServer.java:183) at cn.jja8.newbinggogo.NewBingGoGoServer.serveHttp(NewBingGoGoServer.java:60) at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:862) at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:901) at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:148) at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jianjianai** [comment]
bing不允许从国内访问，需要部署到国外服务器上。
