### ISSUE TITLE
本地部署NBGGW发生错误

### ISSUE THREAD

**Issue by LAGQWQ** [jianjianai/NewBingGoGo-Web#96]
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/112602213/4f4fedf7-e98c-4ee3-b7bf-aed9c2068e12)
我尝试在本地虚拟机部署NBGGW，它提示下面的错误:
```
java.net.ProtocolException: Server redirected too many times (20) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2008) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) at cn.jja8.newbinggogo.NewBingGoGoServer.goUrl(NewBingGoGoServer.java:271) at cn.jja8.newbinggogo.NewBingGoGoServer.serveHttp(NewBingGoGoServer.java:60) at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:862) at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:901) at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:148) at java.base/java.lang.Thread.run(Thread.java:833)
```
是不是必须挂梯子才可以？我的虚拟机使用的是桥接网络模式，下面是终端输出，请阅:
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/112602213/0eb2d2f5-a3c3-492a-a319-31fad77f9a8c)
下面是我的`cookies.yml`配置:
```
joinStats: true
cookies:
- _U=1UBfOdP0lCt2uAmW6RFvrff18nGlyGJQf1T5Kz--Y2J91WtL-8rk_THcIxNtvvYjT2FWJoP7B7KZgA0gAKg0K1N21naW61waqUio68atNGeRaXzvDxuJKw6o_Z1Z16zKrPv9M5Cs8Hfso9cmor6tn_94J_W7a2JNQesaLwjxu8HzXVX-CiAgERwYC30gRCxm-tJ_CjYftd2wxb7h1_KtY2w
```
![image](https://github.com/jianjianai/NewBingGoGo-Web/assets/112602213/f0f90b48-0061-43cf-9ed3-6ad08f4fe4dc)

**Comment by luoluomohe** [comment]
一模一样的报错，也是jar -jar命令启动的，大佬救一下

**Comment by neroxiangkongyue** [comment]
俺也一样😭

**Comment by Fino3** [comment]
我也是，不过我以及挂了ti也不行
